# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tld}
  s.version = "0.6.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["alex"]
  s.date = %q{2011-10-27}
  s.description = %q{Top-level domain library}
  s.email = %q{alexrabarts@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "Manifest.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "lib/tld.rb",
    "lib/tld/alpha3.rb",
    "lib/tld/cc_tld.rb",
    "lib/tld/currency.rb",
    "lib/tld/generic_tld.rb",
    "lib/tld/infrastructure_tld.rb",
    "lib/tld/name.rb",
    "lib/tld/pseudo_tld.rb",
    "lib/tld/reserved_tld.rb",
    "lib/tld/retired_tld.rb",
    "lib/tld/sponsored_tld.rb",
    "lib/tld/tld.rb",
    "rakelib/cultivate.rake",
    "rakelib/tld.rake",
    "rakelib/tld.rb",
    "rakelib/tld.rb.erb",
    "test/tld_test.rb",
    "tld.gemspec"
  ]
  s.homepage = %q{http://github.com/alexrabarts/tld}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Provides meta information for Internet Top Level Domains (TLDs).}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<erubis>, [">= 0"])
      s.add_development_dependency(%q<addressable>, [">= 0"])
      s.add_development_dependency(%q<iso_country_codes>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<erubis>, [">= 0"])
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<iso_country_codes>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<erubis>, [">= 0"])
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<iso_country_codes>, [">= 0"])
  end
end

